---
abstract: 'Tapper - Central master control program of Tapper automation'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  String::Diff: 0
  Tapper::Test: 3.000002
  Test::Fixture::DBIC::Schema: 0
  Test::MockModule: 0
  Test::More: 0.88
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-MCP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Data::Dumper: 0
  Devel::Backtrace: 0
  File::Basename: 0
  File::Path: 0
  File::Path::Tiny: 0
  File::Spec: 0
  IO::Handle: 0
  IO::Select: 0
  IO::Socket::INET: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Declare: 0.27
  MooseX::Traits: 0
  Net::SSH: 0
  Net::SSH::Expect: 0
  Perl6::Junction: 0
  Socket: 0
  Tapper::Base: 3.000002
  Tapper::Cmd: 3.000002
  Tapper::Config: 3.000002
  Tapper::Model: 3.000002
  Tapper::Schema: 3.000002
  Template: 0
  YAML: 0.72
  aliased: 0
  parent: 0
  perl: 5.010
version: 3.000002
